#!/bin/bash

set -e
set -x

LOCKFILE=~/.pbuilder.lock
exec 99>> "$LOCKFILE"
flock 99

MIRROR=http://raspbian.freemirror.org/raspbian/
BASE_URL=https://dfx.at/rtpengine

DISTS='bullseye buster bookworm'


for DIST in $DISTS; do
	sudo cowbuilder --update --mirror "$MIRROR" --override-config --distribution "$DIST" --basepath ~/var/cache/pbuilder/base-"$DIST"-armhf.cow --aptcache ~/var/cache/aptcache --buildplace ~/var/cache/pbuilder/build
done
