#!/bin/bash

set -e
set -x

declare -a errors

EXTRA_MIRROR=http://archive.raspberrypi.org/debian/

#DISTS='bullseye buster stretch bookworm'
DISTS='bullseye bookworm'
ARCHS='armhf arm64'

declare -A MIRRORS
MIRRORS[stretch]=http://archive.debian.org/debian/

SDIR=$1
test -d "$SDIR"
mv -v "$SDIR"/arm-queue/* ~/var/arm-queue/ || true

for DIST in $DISTS; do
	MIRROR=http://deb.debian.org/debian
	if [ -n "${MIRRORS[$DIST]}" ]; then
		MIRROR=${MIRRORS[$DIST]}
	fi
	for QF in ~/var/arm-queue/*."$DIST"; do
		test -f "$QF" || continue

		URL=$(<"$QF")
		FN=$(basename "$QF")

		for ARCH in $ARCHS; do

			BUILDDIR=~/tmp/build.$RANDOM
			OUTPUTDIR=~/tmp/artefacts.$RANDOM

			mkdir "$BUILDDIR"
			mkdir "$OUTPUTDIR"

			cd "$BUILDDIR"
			dget --allow-unauthenticated "$URL"

			set +e
			LOGFILE=build.log.$$."$DIST"-"$ARCH"
			sudo cowbuilder --build --mirror "$MIRROR" --othermirror="deb $EXTRA_MIRROR $DIST main" --override-config --distribution "$DIST" --buildplace ~/var/cache/pbuilder/build --buildresult "$OUTPUTDIR" --basepath ~/var/cache/pbuilder/base-"$DIST"-$ARCH.cow --aptcache ~/var/cache/aptcache *.dsc > "../$LOGFILE" 2>&1
			CODE=$?
			set -e

			cd ..
			rm -rf "$BUILDDIR"

			if test "$CODE" -eq 0; then
				MVDIR="$SDIR"/arm-results/.results.$RANDOM
				mkdir "$MVDIR"
				mv -v "$OUTPUTDIR"/* "$MVDIR"
				mv -v "$MVDIR" "$SDIR"/arm-results/results."$FN".$RANDOM."$DIST"
				rmdir "$OUTPUTDIR"
				rm -f "$LOGFILE"

			else
				echo build failed
				echo build log: "$LOGFILE"
				mv "$LOGFILE" ~/
				errors+=("build failed: $LOGFILE")
			fi

		done

		rm -f "$QF"
	done
done


if test ${#errors[@]} -gt 0; then
	echo errors:
	echo "${errors[@]}"
	exit 1
fi

exit 0
