#!/bin/bash

set -e
set -x

LOCKFILE=~/.buildscript.lock
exec 99>> "$LOCKFILE"
flock -n 99 || exit 0

BUILDER_LOCK=~/.pbuilder.lock
exec 98>> "$BUILDER_LOCK"
flock 98


MIRROR=http://raspbian.freemirror.org/raspbian/

DISTS='bullseye buster bookworm stretch'


test -d ~/dfx.at-var
mv -v ~/dfx.at-var/arm-queue/* ~/var/arm-queue/ || true

for DIST in $DISTS; do
	for QF in ~/var/arm-queue/*."$DIST"; do
		test -f "$QF" || continue

		URL=$(<"$QF")
		FN=$(basename "$QF")

		BUILDDIR=~/tmp/build.$RANDOM
		OUTPUTDIR=~/tmp/artefacts.$RANDOM

		mkdir "$BUILDDIR"
		mkdir "$OUTPUTDIR"

		cd "$BUILDDIR"
		dget --allow-unauthenticated "$URL"
		sudo cowbuilder --build --mirror "$MIRROR" --override-config --distribution "$DIST" --buildplace ~/var/cache/pbuilder/build --buildresult "$OUTPUTDIR" --basepath ~/var/cache/pbuilder/base-"$DIST"-armhf.cow --aptcache ~/var/cache/aptcache *.dsc
		cd ..
		rm -rf "$BUILDDIR"

		MVDIR=~/dfx.at-var/arm-results/.results.$RANDOM
		mkdir "$MVDIR"
		mv -v "$OUTPUTDIR"/* "$MVDIR"
		mv -v "$MVDIR" ~/dfx.at-var/arm-results/results."$FN".$RANDOM."$DIST"
		rmdir "$OUTPUTDIR"

		rm -f "$QF"
	done
done
