#!/bin/bash

set -e
set -x

declare -a errors

DISTS='sid trixie bookworm'
ARCHS='armhf arm64'

SDIR=$1
test -d "$SDIR"
TDIR=$2
test -d "$TDIR"
mv -v "$SDIR"/arm-queue2/* "$TDIR"/ || true

for DIST in $DISTS; do
	for QF in "$TDIR"/*."$DIST"; do
		test -f "$QF" || continue

		URL=$(<"$QF")
		FN=$(basename "$QF")

		for ARCH in $ARCHS; do
			IMAGE=~/var/cache/pbuilder/debian-$DIST-$ARCH.tar.zst
			BUILDDIR=~/tmp/build.$RANDOM
			OUTPUTDIR=~/tmp/artefacts.$RANDOM

			mkdir "$BUILDDIR"
			mkdir "$OUTPUTDIR"

			cd "$BUILDDIR"
			zstdcat "$IMAGE" | tar -xv
			mkdir build
			cd build

			dget --allow-unauthenticated "$URL"

			set +e
			LOGFILE=build.log.$$."$DIST"-"$ARCH"
			echo debuild \*.dsc > script
			sudo chroot . bash script > ../../"$LOGFILE" 2>&1
			CODE=$?
			set -e

			##### XXX
			cd .
			cd ..
			rm -rf "$BUILDDIR"

			if test "$CODE" -eq 0; then
				MVDIR="$SDIR"/arm-results/.results.$RANDOM
				mkdir "$MVDIR"
				mv -v "$OUTPUTDIR"/* "$MVDIR"
				mv -v "$MVDIR" "$SDIR"/arm-results/results."$FN".$RANDOM."$DIST"
				rmdir "$OUTPUTDIR"
				rm -f "$LOGFILE"

			else
				echo build failed
				echo build log: "$LOGFILE"
				mv "$LOGFILE" ~/
				errors+=("build failed: $LOGFILE")
			fi

		done

		rm -f "$QF"
	done
done


if test ${#errors[@]} -gt 0; then
	echo errors:
	echo "${errors[@]}"
	exit 1
fi

exit 0
