#!/bin/bash

set -e

INPUT=~/var/arm-results

for D in "$INPUT"/results.*; do
	BD=$(basename "$D")

	if [[ "$BD" =~ \.([a-z]+)$ ]]; then
		DIST=${BASH_REMATCH[1]}
	else
		continue
	fi

	if [[ "$BD" =~ ^results\.([a-z-]+)\. ]]; then
		PKG=${BASH_REMATCH[1]}
	else
		continue
	fi

	case "$PKG" in
		rtpengine)
			REPO=~/htdocs/dfx.at/rtpengine
			SUB_REPO=true
			;;
		subsurface|subsurface-beta)
			REPO=~/htdocs/dfx.at/subsurface
			SUB_REPO=false
			;;
		*)
			continue
	esac

	for F in "$D"/*; do
		case "$F" in
			*_armhf.deb|*_arm64.deb)
				;;
			*)
				rm -f "$F" || true
				continue
				;;
		esac

		REPO_DST=$REPO

		if $SUB_REPO; then
			if [[ "$F" =~ _[0-9]+~ ]]; then
				REL=beta
			elif [[ "$F" =~ _([0-9]+\.[0-9]+)\.[0-9]+\.[0-9]+- ]]; then
				REL=${BASH_REMATCH[1]}
			else
				rm -f "$F"
				continue
			fi
			REPO_DST="$REPO"/"$REL"
		fi

		reprepro -Vb "$REPO_DST" -C main includedeb "$DIST" "$F"
		rm -f "$F"
	done

	rmdir "$D"
done
