#!/bin/bash

set -e
set -x

LOCKFILE=~/.pbuilder.lock
exec 99>> "$LOCKFILE"
flock 99

MIRROR=http://deb.debian.org/debian
EXTRA_MIRROR=http://archive.raspberrypi.org/debian/
BASE_URL=https://dfx.at/rtpengine

DISTS='stretch bullseye buster'
ARCHS='armhf arm64'


for DIST in $DISTS; do
	for ARCH in $ARCHS; do
		sudo cowbuilder --update --mirror "$MIRROR" --othermirror="deb $EXTRA_MIRROR $DIST main" --override-config --distribution "$DIST" --basepath ~/var/cache/pbuilder/base-"$DIST"-"$ARCH".cow --aptcache ~/var/cache/aptcache --buildplace ~/var/cache/pbuilder/build
	done
done
