#!/bin/bash

set -e

INPUT=~/var/arm-results

for D in "$INPUT"/results.*; do
	BD=$(basename "$D")

	if [[ "$BD" =~ \.([a-z]+)$ ]]; then
		DIST=${BASH_REMATCH[1]}
	else
		continue
	fi

	if [[ "$BD" =~ ^results\.([a-z]+)\. ]]; then
		PKG=${BASH_REMATCH[1]}
	else
		continue
	fi

	case "$PKG" in
		rtpengine)
			REPO=~/htdocs/dfx.at/rtpengine
			;;
		*)
			continue
	esac

	for F in "$D"/*; do
		case "$F" in
			*_armhf.deb)
				;;
			*)
				rm -f "$F" || true
				continue
				;;
		esac

		if [[ "$F" =~ _[0-9]+~ ]]; then
			REL=beta
		elif [[ "$F" =~ _([0-9]+\.[0-9]+)\.[0-9]+\.[0-9]+- ]]; then
			REL=${BASH_REMATCH[1]}
		else
			rm -f "$F"
			continue
		fi

		reprepro -Vb "$REPO"/"$REL" -C main includedeb "$DIST" "$F"
		rm -f "$F"
	done

	rmdir "$D"
done
