#!/bin/bash

set -e
set -x

TAG_FILE=~/.rtpe.all.tags.new

test -f "$TAG_FILE" || exit 0

for BRANCH in latest 8.5 9.5 10.0 10.1; do
	CUR_FILE=~/.rtpe.branch."$BRANCH".last.tag.cur
	if test "$BRANCH" = latest; then
		NEW_TAG=$(grep ^mr "$TAG_FILE" | tail -n 1)
	else
		NEW_TAG=$(grep ^mr"$BRANCH"\\. "$TAG_FILE" | tail -n 1)
	fi

	if ! test -f "$CUR_FILE"; then
		true
	else
		CUR_TAG=$(<"$CUR_FILE")
		test -n "$NEW_TAG"
		test "$NEW_TAG" = "$CUR_TAG" && continue
	fi

	"$RTPENGINE_DEBIAN_SRCDIR"/"$BRANCH"/build-all "$NEW_TAG"

	echo "$NEW_TAG" > "$CUR_FILE"
done
