#!/bin/bash

set -e
set -x

DISTS='forky bullseye bookworm trixie sid'
ARCHS='amd64 i386 armhf arm64'

SRCDIR=$1
test -d "$SRCDIR"
DSTDIR=$2
test -d "$DSTDIR"
TMPDIR=$3
test -d "$TMPDIR"

mv -v "$SRCDIR"/* "$TMPDIR"/ || true

for DIST in $DISTS; do
	for FILE in "$TMPDIR"/*."$DIST"; do
		BN=$(basename "$FILE") # rtpengine.beta.sid | rtpengine.26.0.sid

		for ARCH in $ARCHS; do
			DD="$DSTDIR"/"$ARCH"/"$DIST"
			mkdir -p "$DD"
			cp -v "$FILE" "$DD"/."$BN".$$
			mv -v "$DD"/."$BN".$$ "$DD"/"$BN"
		done
	done

	rm -f "$FILE"
done
