#!/bin/bash

set -e
set -x

DISTS='forky bullseye bookworm trixie sid'
ARCHS='amd64 i386 armhf arm64'

SRCDIR=$1
test -d "$SRCDIR"
DSTDIR=$2
test -d "$DSTDIR"
TMPDIR=$3
test -d "$TMPDIR"


for DIST in $DISTS; do
	test -d "$SRCDIR"/"$DIST" || continue

	mkdir -p "$TMPDIR"/"$DIST"
	mv -v "$SRCDIR"/"$DIST"/* "$TMPDIR"/"$DIST"/ || true

	for FILE in "$TMPDIR"/"$DIST"/*; do
		test -e "$FILE" || continue

		BN=$(basename "$FILE") # rtpengine.beta | rtpengine.26.0 | subsurface-qt6

		for ARCH in $ARCHS; do
			DD="$DSTDIR"/"$ARCH"/"$DIST"
			mkdir -p "$DD"
			cp -v "$FILE" "$DD"/."$BN".$$
			mv -v "$DD"/."$BN".$$ "$DD"/"$BN"
		done

		rm -f "$FILE"
	done
done
