#!/bin/bash

set -e
set -x

RELEASES='sid bullseye buster bookworm trixie'
ARCHS='amd64 i386'

declare -A MIRRORS
MIRRORS[stretch]=http://archive.debian.org/debian/

for RELEASE in $RELEASES; do
	MIRROR=http://deb.debian.org/debian
	if [ -n "${MIRRORS[$RELEASE]}" ]; then
		MIRROR=${MIRRORS[$RELEASE]}
	fi
	for ARCH in $ARCHS; do
		# sudo pbuilder --create --basetgz ~/var/cache/pbuilder/base-trixie-amd64.tgz --distribution trixie --architecture amd64 --mirror http://deb.debian.org/debian --override-config --aptcache ~/var/cache/aptcache --buildplace ~/var/build
		sudo pbuilder update --basetgz ~/var/cache/pbuilder/base-"$RELEASE"-"$ARCH".tgz --distribution "$RELEASE" --mirror "$MIRROR" --override-config --aptcache ~/var/cache/aptcache --buildplace ~/var/build
	done
done
