#!/bin/bash

set -e
set -x

git clone --branch "$TAG" https://github.com/sipwise/rtpengine.git

sed -i 's/^Maintainer: .*/Maintainer: Richard Fuchs <dfx@dfx.at>/' rtpengine/debian/control*
sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' rtpengine/utils/build_test_wrapper

test ! -e rtpengine-"$VERSION"
mkdir rtpengine-"$VERSION"

cp -va rtpengine/. rtpengine-"$VERSION"
rm -rf rtpengine-"$VERSION"/.git
tar -czf rtpengine_"$VERSION".orig.tar.gz rtpengine-"$VERSION"
rm -rf rtpengine

echo export VERSION="$VERSION"
