#!/bin/bash

set -e
set -x

git clone --branch "$TAG" https://github.com/sipwise/rtpengine.git

test ! -e rtpengine-"$VERSION"
mkdir rtpengine-"$VERSION"

cp -va rtpengine/. rtpengine-"$VERSION"

pushd rtpengine-"$VERSION"
rename 's/ngcp-rtpengine/rtpengine/' debian/ngcp-rtpengine*
find debian -type f -print0 | xargs -0 sed -i 's/ngcp-rtpengine/rtpengine/g'
echo '3.0 (quilt)' > debian/source/format

patch -p0 << 'EOF'
diff -ur debian.orig/control debian/control
--- debian.orig/control	2021-10-29 00:32:52.707680372 +0200
+++ debian/control	2021-10-29 00:36:12.578441728 +0200
@@ -53,6 +53,7 @@
  ${shlibs:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-daemon,
+ ngcp-rtpengine-daemon,
  rtpengine-redis1,
 Replaces:
  ngcp-mediaproxy-ng-daemon,
@@ -72,6 +73,8 @@
  nfs-common,
  ${misc:Depends},
  ${shlibs:Depends},
+Conflicts:
+ ngcp-rtpengine-recording-daemon,
 Description: recording daemon for RTP and media streams
  This daemon handles the call recording (media intercept) component of rtpengine.
 
@@ -82,6 +85,7 @@
  ${shlibs:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-iptables,
+ ngcp-rtpengine-iptables,
 Replaces:
  ngcp-mediaproxy-ng-iptables,
 Description: IPtables extension module for the kernel-space NGCP media proxy
@@ -114,6 +118,7 @@
  ${misc:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-kernel-source,
+ ngcp-rtpengine-kernel-source,
 Replaces:
  ngcp-mediaproxy-ng-kernel-source,
 Description: IPtables kernel module for the NGCP media proxy - source
@@ -133,6 +138,7 @@
  ${misc:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-kernel-dkms,
+ ngcp-rtpengine-kernel-dkms,
 Replaces:
  ngcp-mediaproxy-ng-kernel-dkms,
 Description: IPtables kernel module for the NGCP media proxy - DKMS
@@ -153,5 +159,7 @@
  netcat-openbsd | netcat,
  ${misc:Depends},
  ${perl:Depends},
+Conflicts:
+ ngcp-rtpengine-utils,
 Description: scripts and Perl modules for NGCP rtpengine
  This package contains scripts and Perl modules for NGCP rtpengine
diff -ur debian.orig/control.modules.in debian/control.modules.in
--- debian.orig/control.modules.in	2021-10-29 00:32:52.707680372 +0200
+++ debian/control.modules.in	2021-10-29 00:36:41.301688868 +0200
@@ -13,6 +13,8 @@
  linux-modules-_KVERS_ | linux-image-_KVERS_,
 Provides:
  rtpengine-kernel,
+Conflicts:
+ ngcp-rtpengine-kernel-modules-_KVERS_,
 Description: IPtables kernel module for the NGCP media proxy
  This package provides the rtpengine module for
  the Linux kernel version _KVERS_.
EOF

popd
tar -czf rtpengine_"$VERSION".orig.tar.gz rtpengine-"$VERSION"
rm -rf rtpengine

echo export VERSION="$VERSION"
