#!/bin/bash

set -e
set -x

git clone --branch "$TAG" https://github.com/sipwise/rtpengine.git

sed -i 's/^Maintainer: .*/Maintainer: Richard Fuchs <dfx@dfx.at>/' rtpengine/debian/control*

test ! -e rtpengine-"$VERSION"
mkdir rtpengine-"$VERSION"

cp -va rtpengine/. rtpengine-"$VERSION"

pushd rtpengine-"$VERSION"
rename 's/ngcp-rtpengine/rtpengine/g' debian/ngcp-rtpengine*
find debian -type f -print0 | xargs -0 sed -i 's/ngcp-rtpengine/rtpengine/g'
echo '3.0 (quilt)' > debian/source/format

patch -p0 << 'EOF'
diff -ur debian.orig/control debian/control
--- debian.orig/control	2021-10-29 10:18:57.545208462 -0400
+++ debian/control	2021-10-29 10:20:00.429016466 -0400
@@ -45,14 +45,13 @@
 Recommends:
  rtpengine-recording-daemon,
  rtpengine-utils,
-Suggests:
- ngcp-system-tools,
 Depends:
  lsb-base (>= 3.0-6),
  ${misc:Depends},
  ${shlibs:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-daemon,
+ ngcp-rtpengine-daemon,
  rtpengine-redis1,
 Replaces:
  ngcp-mediaproxy-ng-daemon,
@@ -65,13 +64,13 @@
 Architecture: any
 Recommends:
  rtpengine-utils,
-Suggests:
- ngcp-system-tools,
 Depends:
  lsb-base (>= 3.0-6),
  nfs-common,
  ${misc:Depends},
  ${shlibs:Depends},
+Conflicts:
+ ngcp-rtpengine-recording-daemon,
 Description: recording daemon for RTP and media streams
  This daemon handles the call recording (media intercept) component of rtpengine.
 
@@ -82,6 +81,7 @@
  ${shlibs:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-iptables,
+ ngcp-rtpengine-iptables,
 Replaces:
  ngcp-mediaproxy-ng-iptables,
 Description: IPtables extension module for the kernel-space NGCP media proxy
@@ -114,6 +114,7 @@
  ${misc:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-kernel-source,
+ ngcp-rtpengine-kernel-source,
 Replaces:
  ngcp-mediaproxy-ng-kernel-source,
 Description: IPtables kernel module for the NGCP media proxy - source
@@ -125,14 +126,13 @@
 Package: rtpengine-kernel-dkms
 Architecture: all
 Section: kernel
-Suggests:
- ngcp-system-tools,
 Depends:
  dkms (>= 1.95),
  lsb-release,
  ${misc:Depends},
 Conflicts:
  ngcp-mediaproxy-ng-kernel-dkms,
+ ngcp-rtpengine-kernel-dkms,
 Replaces:
  ngcp-mediaproxy-ng-kernel-dkms,
 Description: IPtables kernel module for the NGCP media proxy - DKMS
@@ -153,5 +153,7 @@
  netcat-openbsd | netcat,
  ${misc:Depends},
  ${perl:Depends},
+Conflicts:
+ ngcp-rtpengine-utils,
 Description: scripts and Perl modules for NGCP rtpengine
  This package contains scripts and Perl modules for NGCP rtpengine
diff -ur debian.orig/control.modules.in debian/control.modules.in
--- debian.orig/control.modules.in	2021-10-29 10:18:57.549208449 -0400
+++ debian/control.modules.in	2021-10-29 10:19:07.929176793 -0400
@@ -13,6 +13,8 @@
  linux-modules-_KVERS_ | linux-image-_KVERS_,
 Provides:
  rtpengine-kernel,
+Conflicts:
+ ngcp-rtpengine-kernel-modules-_KVERS_,
 Description: IPtables kernel module for the NGCP media proxy
  This package provides the rtpengine module for
  the Linux kernel version _KVERS_.
EOF

popd
tar -czf rtpengine_"$VERSION".orig.tar.gz rtpengine-"$VERSION"
rm -rf rtpengine

echo export VERSION="$VERSION"
