#!/bin/bash

set -e
set -x

git clone --branch "$TAG" https://github.com/sipwise/rtpengine.git

test ! -e rtpengine-"$VERSION"
mkdir rtpengine-"$VERSION"

cp -va rtpengine/. rtpengine-"$VERSION"
tar -czf rtpengine_"$VERSION".orig.tar.gz rtpengine-"$VERSION"
rm -rf rtpengine

echo export VERSION="$VERSION"
