#!/bin/bash

set -e
set -x

LAST_BUILD_ID=~/.rtpe.last.build.id
BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/rtpengine/beta
RELEASES='forky,~bpo14+1 bookworm,~bpo12+1 bullseye,~bpo11+1 trixie,~bpo13+1 sid,'

test -n "$RTPENGINE_DEBIAN_SRCDIR"

cd "$BUILDDIR"
mkdir build.$$

cd build.$$

export VERSION=$(date +%Y%m%d%H%M)

export LAST_BUILD_ID
export THIS_BUILD_ID="$LAST_BUILD_ID.new"
export FULL_VER_ID="$LAST_BUILD_ID.full.ver"

rm -f "$FULL_VER_ID"
set +e
"$RTPENGINE_DEBIAN_SRCDIR"/beta/create-source-package
CODE=$?
set -e

if test "$CODE" -ne 0; then
	cd ..
	rm -rf build.$$
	if test "$CODE" -eq 42; then
		exit 0
	fi
	exit "$CODE"
fi

if test -f "$FULL_VER_ID"; then
	FULL_VERSION=$(<"$FULL_VER_ID")
	VERSION=$FULL_VERSION
fi

set +x

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	FULL_VER="$VERSION"-1"$REL_CODE"
	REL_NAME=$RELEASE
	if test "$REL_NAME" = sid; then
		REL_NAME=unstable
	fi
	export RELEASE
	export REL_CODE
	export FULL_VER
	export REL_NAME
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$RTPENGINE_DEBIAN_SRCDIR"/beta/create-debian-build
	debsign rtpengine_"$FULL_VER".dsc
	reprepro -Vb "$REPO" -C main -P optional -S net includedsc "$RELEASE" rtpengine_"$FULL_VER".dsc

	if test -d ~/var/src-build-q; then
		mkdir -p ~/var/src-build-q/"$RELEASE"
		echo https://dfx.at/rtpengine/beta/pool/main/r/rtpengine/rtpengine_"$FULL_VER".dsc > ~/var/src-build-q/"$RELEASE"/.rtpengine.beta.$$ || true
		mv ~/var/src-build-q/"$RELEASE"/.rtpengine.beta.$$ ~/var/src-build-q/"$RELEASE"/rtpengine.beta || true
	fi
	cd ..
done

cd ..
rm -rf build.$$

mv -f "$THIS_BUILD_ID" "$LAST_BUILD_ID"

exit 0
