#!/bin/bash

set -e
set -x

test -n "$RELEASE"
test -n "$RTPENGINE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

test -f ../rtpengine_"$VERSION".orig.tar.gz
test -d ../rtpengine-"$VERSION"

cp -va ../rtpengine_"$VERSION".orig.tar.gz ../rtpengine-"$VERSION" .

pushd rtpengine-"$VERSION"

test -f pkg/deb/backports/"$RELEASE"
test -d debian
pushd pkg/deb
./generator.sh
./backports/"$RELEASE"
test -d "$RELEASE"
rm -rf debian
popd
rm -rf debian
mv -v pkg/deb/"$RELEASE" debian
echo '3.0 (quilt)' > debian/source/format

dch -v "$FULL_VER" -D "$RELEASE" --force-distribution --package rtpengine "Beta build"

popd

dpkg-source -b rtpengine-"$VERSION"

test -d ~/var/arm-queue && echo beta/pool/main/r/rtpengine/rtpengine_"$FULL_VER".dsc > ~/var/arm-queue/rtpengine.beta."$RELEASE" || true
