#!/bin/bash

set -e
set -x

if test -z "$VERSION"; then
	VERSION=$(date +%Y%m%d%H%M)
fi

git clone https://github.com/sipwise/rtpengine.git

cd rtpengine

if test -n "$BRANCH"; then
	 git checkout "$BRANCH"
fi

git tag --sort=version:refname > ~/.rtpe.all.tags.$$
git branch -r --sort=version:refname > ~/.rtpe.all.branches.$$
cd ..
mv -f ~/.rtpe.all.tags.$$ ~/.rtpe.all.tags.new
mv -f ~/.rtpe.all.branches.$$ ~/.rtpe.all.branches.new

if test -n "$THIS_BUILD_ID"; then
	cd rtpengine

	THIS_ID=$(git rev-parse HEAD)
	if test -n "$LAST_BUILD_ID" -a -f "$LAST_BUILD_ID"; then
		LAST_ID=$(<"$LAST_BUILD_ID")
		if test "$LAST_ID" = "$THIS_ID"; then
			echo no new commits
			exit 42
		fi
	fi

	echo "$THIS_ID" > "$THIS_BUILD_ID"
	cd ..
fi

SHORT_ID=${THIS_ID:0:8}
FULL_VERSION="$VERSION~$SHORT_ID"

if test -n "$FULL_VER_ID"; then
	echo "$FULL_VERSION" > "$FULL_VER_ID"
	VERSION=$FULL_VERSION
fi

sed -i 's/^Maintainer: .*/Maintainer: Richard Fuchs <dfx@dfx.at>/' rtpengine/debian/control*
sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' rtpengine/utils/build_test_wrapper

test ! -e rtpengine-"$VERSION"
mkdir rtpengine-"$VERSION"

cp -va rtpengine/. rtpengine-"$VERSION"
rm -rf rtpengine-"$VERSION"/.git
tar -czf rtpengine_"$VERSION".orig.tar.gz rtpengine-"$VERSION"
rm -rf rtpengine

echo export VERSION="$VERSION"
