#!/bin/bash

set -e
set -x

if test -z "$VERSION"; then
	VERSION=$(date +%Y%m%d%H%M)
fi

git clone https://github.com/sipwise/rtpengine.git

cd rtpengine
git tag > ~/.rtpe.all.tags.$$
git branch -r > ~/.rtpe.all.branches.$$
cd ..
mv -f ~/.rtpe.all.tags.$$ ~/.rtpe.all.tags.new
mv -f ~/.rtpe.all.branches.$$ ~/.rtpe.all.branches.new

if test -n "$THIS_BUILD_ID"; then
	cd rtpengine

	THIS_ID=$(git rev-parse HEAD)
	if test -n "$LAST_BUILD_ID" -a -f "$LAST_BUILD_ID"; then
		LAST_ID=$(<"$LAST_BUILD_ID")
		if test "$LAST_ID" = "$THIS_ID"; then
			echo no new commits
			exit 42
		fi
	fi

	echo "$THIS_ID" > "$THIS_BUILD_ID"
	cd ..
fi

SHORT_ID=${THIS_ID:0:8}
FULL_VERSION="$VERSION~$SHORT_ID"

if test -n "$FULL_VER_ID"; then
	echo "$FULL_VERSION" > "$FULL_VER_ID"
	VERSION=$FULL_VERSION
fi

test ! -e rtpengine-"$VERSION"
mkdir rtpengine-"$VERSION"

cp -va rtpengine/. rtpengine-"$VERSION"

pushd rtpengine-"$VERSION"
rename 's/ngcp-rtpengine/rtpengine/' debian/ngcp-rtpengine*
find debian -type f -print0 | xargs -0 sed -i 's/ngcp-rtpengine/rtpengine/g'
echo '3.0 (quilt)' > debian/source/format

patch -p0 << 'EOF'
diff -ur debian.orig/control debian/control
--- debian.orig/control	2021-10-29 10:08:34.383082012 -0400
+++ debian/control	2021-10-29 10:08:51.451031439 -0400
@@ -49,13 +49,13 @@
 Recommends:
  rtpengine-recording-daemon,
  rtpengine-utils,
-Suggests:
- ngcp-system-tools,
 Depends:
  iptables,
  lsb-base (>= 3.0-6),
  ${misc:Depends},
  ${shlibs:Depends},
+Conflicts:
+ ngcp-rtpengine-daemon,
 Description: proxy for RTP and media streams used in NGCP, userspace part
  This daemon handles the first stages of proxying media streams and talks to
  the kernel part of the proxy for eventual high-performance packet forwarding.
@@ -65,13 +65,13 @@
 Build-Profiles: <!pkg.rtpengine.no-transcoding>
 Recommends:
  rtpengine-utils,
-Suggests:
- ngcp-system-tools,
 Depends:
  lsb-base (>= 3.0-6),
  nfs-common,
  ${misc:Depends},
  ${shlibs:Depends},
+Conflicts:
+ ngcp-rtpengine-recording-daemon,
 Description: recording daemon for RTP and media streams
  This daemon handles the call recording (media intercept) component of rtpengine.
 
@@ -80,6 +80,8 @@
 Depends:
  ${misc:Depends},
  ${shlibs:Depends},
+Conflicts:
+ ngcp-rtpengine-iptables,
 Description: IPtables extension module for the kernel-space NGCP media proxy
  Provides the IPtables extension needed to configure the mediaproxy rule.
 
@@ -104,6 +106,8 @@
  debhelper-compat (= 12),
  module-assistant,
  ${misc:Depends},
+Conflicts:
+ ngcp-rtpengine-kernel-source,
 Description: IPtables kernel module for the NGCP media proxy - source
  Provides the kernel-space part of the NGCP media proxy for high-
  performance packet forwarding.
@@ -113,12 +117,12 @@
 Package: rtpengine-kernel-dkms
 Architecture: all
 Section: kernel
-Suggests:
- ngcp-system-tools,
 Depends:
  dkms (>= 1.95),
  lsb-release,
  ${misc:Depends},
+Conflicts:
+ ngcp-rtpengine-kernel-dkms,
 Description: IPtables kernel module for the NGCP media proxy - DKMS
  Provides the kernel-space part of the NGCP media proxy for high-
  performance packet forwarding.
@@ -137,5 +141,7 @@
  netcat-openbsd | netcat,
  ${misc:Depends},
  ${perl:Depends},
+Conflicts:
+ ngcp-rtpengine-utils,
 Description: scripts and Perl modules for NGCP rtpengine
  This package contains scripts and Perl modules for NGCP rtpengine
diff -ur debian.orig/control.modules.in debian/control.modules.in
--- debian.orig/control.modules.in	2021-10-29 10:08:34.383082012 -0400
+++ debian/control.modules.in	2021-10-29 10:08:39.651066407 -0400
@@ -13,6 +13,8 @@
  linux-modules-_KVERS_ | linux-image-_KVERS_,
 Provides:
  rtpengine-kernel,
+Conflicts:
+ ngcp-rtpengine-kernel-modules-_KVERS_,
 Description: IPtables kernel module for the NGCP media proxy
  This package provides the rtpengine module for
  the Linux kernel version _KVERS_.
EOF

popd
tar -czf rtpengine_"$VERSION".orig.tar.gz rtpengine-"$VERSION"
rm -rf rtpengine

echo export VERSION="$VERSION"
