#!/bin/bash

set -e
set -x

test -n "$RELEASE"
test -n "$RTPENGINE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

test -f ../rtpengine-beta_"$VERSION".orig.tar.gz
test -d ../rtpengine-beta-"$VERSION"

cp -va ../rtpengine-beta_"$VERSION".orig.tar.gz ../rtpengine-beta-"$VERSION" .
cd rtpengine-beta-"$VERSION"

case "$RELEASE" in
	buster)
		# bcg729 is not available in buster
		sed -i '/bcg729/d' debian/control
		;;
esac

dch -v "$FULL_VER" -D "$RELEASE" --package rtpengine-beta "Beta build"
cd ..
dpkg-source -b rtpengine-beta-"$VERSION"
