#!/bin/bash

set -e
set -x

test -n "$RELEASE"
test -n "$RTPENGINE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

test -f ../rtpengine_"$VERSION".orig.tar.gz
test -d ../rtpengine-"$VERSION"

cp -va ../rtpengine_"$VERSION".orig.tar.gz ../rtpengine-"$VERSION" .

pushd rtpengine-"$VERSION"

test -d pkg/deb/"$RELEASE"
test ! -e debian
cp -vr pkg/deb/"$RELEASE" debian

dch -v "$FULL_VER" --create -D "$RELEASE" --force-distribution --package rtpengine "Beta build"

popd

dpkg-source -b rtpengine-"$VERSION"
