#!/bin/bash

set -e
set -x

test -n "$RELEASE"
test -n "$RTPENGINE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

test -f ../rtpengine_"$VERSION".orig.tar.gz
test -d ../rtpengine-"$VERSION"

cp -va ../rtpengine_"$VERSION".orig.tar.gz ../rtpengine-"$VERSION" .
cd rtpengine-"$VERSION"

case "$RELEASE" in
	buster)
		# bcg729 is not available in buster
		sed -i '/bcg729/d' debian/control
		;;
esac

dch -v "$FULL_VER" -D "$RELEASE" -b --package rtpengine "Build version $VERSION"
cd ..
dpkg-source -b rtpengine-"$VERSION"
