#!/bin/bash

set -e
set -x

TAG="$1"
BRANCH="$2"
BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/rtpengine/"$BRANCH"
RELEASES='forky,~bpo14+1 bookworm,~bpo12+1 bullseye,~bpo11+1 trixie,~bpo13+1 sid,'

test -n "$RTPENGINE_DEBIAN_SRCDIR"
test -n "$TAG"
test -n "$BRANCH"

export TAG

if test -z "$BUILD"; then
	BUILD=1
fi

VERSION=${TAG#mr}
test -n "$VERSION"
export VERSION

cd "$BUILDDIR"
mkdir build.$$

cd build.$$

if test -z "$REBUILD"; then
	if test -e "$REPO"/pool/main/r/rtpengine/rtpengine_"$VERSION".orig.tar.gz; then
		cp "$REPO"/pool/main/r/rtpengine/rtpengine_"$VERSION".orig.tar.gz .
		tar -xf rtpengine_"$VERSION".orig.tar.gz
	else
		"$RTPENGINE_DEBIAN_SRCDIR"/"$BRANCH"/create-source-package
	fi
fi

set +x

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	FULL_VER="$VERSION"-"$BUILD""$REL_CODE"
	REL_NAME=$RELEASE
	if test "$REL_NAME" = sid; then
		REL_NAME=unstable
	fi
	export RELEASE
	export REL_CODE
	export FULL_VER
	export REL_NAME
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$RTPENGINE_DEBIAN_SRCDIR"/"$BRANCH"/create-debian-build
	debsign rtpengine_"$FULL_VER".dsc

	if test -z "$SKIP_REPO"; then
		reprepro -Vb "$REPO" -C main -P optional -S net includedsc "$RELEASE" rtpengine_"$FULL_VER".dsc

		if test -d ~/var/src-build-q; then
			mkdir -p ~/var/src-build-q/"$RELEASE"
			echo https://dfx.at/rtpengine/"$BRANCH"/pool/main/r/rtpengine/rtpengine_"$FULL_VER".dsc > ~/var/src-build-q/"$RELEASE"/.rtpengine."$BRANCH".$$ || true
			mv ~/var/src-build-q/"$RELEASE"/.rtpengine."$BRANCH".$$ ~/var/src-build-q/"$RELEASE"/rtpengine."$BRANCH" || true
		fi
	fi

	cd ..
done

cd ..

if test -z "$SKIP_REPO"; then
	rm -rf build.$$
fi

exit 0
