Document: rtpengine-dfx-repo-keyring
Title: Debian rtpengine-dfx-repo-keyring Manual
Author: <insert document author here>
Abstract: This manual describes what rtpengine-dfx-repo-keyring is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtpengine-dfx-repo-keyring/rtpengine-dfx-repo-keyring.sgml.gz

Format: postscript
Files: /usr/share/doc/rtpengine-dfx-repo-keyring/rtpengine-dfx-repo-keyring.ps.gz

Format: text
Files: /usr/share/doc/rtpengine-dfx-repo-keyring/rtpengine-dfx-repo-keyring.text.gz

Format: HTML
Index: /usr/share/doc/rtpengine-dfx-repo-keyring/html/index.html
Files: /usr/share/doc/rtpengine-dfx-repo-keyring/html/*.html
